services:
  redis:  
    image: redis:6.2.6
    container_name: redis-auth
    volumes:
      - redis_auth:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - etl-network     
    command: redis-server /usr/local/etc/redis/redis.conf
  postgres:
    image: postgres:14.0
    container_name: postgres-auth
    volumes:
      - postgres_auth:/var/lib/postgresql/data/
      - ./postgres:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    networks:
      - etl-network
  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  app:
    container_name: auth-app
    build:
      context: .
      target: prod
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - postgres
      - jaeger
    volumes:
      - ./src/app:/code/app
      - ./src/manage.py:/code/manage.py
    env_file:
      - .env
    networks:
      - etl-network
  nginx:
    image: nginx:1.21.5
    container_name: auth-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - etl-network
volumes:
  redis_auth:
    driver: local
  postgres_auth:
    driver: local

networks:
  etl-network:
    external: true
    driver: bridge